version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./etc_nginx_conf.d/:/etc/nginx/conf.d/
      - ./etc_nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./usr_share_nginx_html/:/usr/share/nginx/html/
    restart: always
  php:
    image: php:8-fpm
    volumes:
      - ./usr_share_nginx_html/:/usr/share/nginx/html/
    restart: always
